### ISSUE TITLE
Custom Local DataSource for Earth2MIP

### ISSUE THREAD

**Issue by jejjohnson** [jejjohnson/jbayesevt#12]
This pull request will create a custom data source that uses local files to load the appropriate variables. It will mimic the `earth2mip` framework which I find is the most flexible. In particular, the [initial conditions](https://github.com/NVIDIA/earth2mip/blob/main/earth2mip/initial_conditions/cds.py) API.

***
### Tasks

- [X] [Interface `local.DataSource` with current code base](#10)
- [X] [Check Compatibility of Variables](#10)
- [X] [Run Full Inference Loop](#10)
- [x] Do for NetCDF Files.

***
### **Simple Psuedo-Code Demo**

```python
# import packages
from earth2mip.initial_conditions import cds, local
# get names of variables
in_channel_names: List[str] = ...
# initialise data source
data_source = cds.DataSource(in_channel_names)
data_source = local.DataSource(in_channel_names)
# run inference loop
ds = run_basic_inference(data_source=data_source, ...)
```

**Comment by jejjohnson** [comment]
Closing do to #22
