### ISSUE TITLE
Geo Preprocessing

### ISSUE THREAD

**Issue by jejjohnson** [jejjohnson/jbayesevt#15]
We want a generalized Preprocessing Pipeline for the geoscience data.

***
**Tasks**

> We want MVP functions for the following tasks.

- [ ] Region Selection
- [ ] Calculate Climatology
- [ ] Filtering - remove high/low frequency signals
- [ ] Spatial Binning - Removing Spatial Dependencies
- [ ] Temporal Period + Frequency Selection
- [ ] Temporal Resampling - Removing Temporal Dependencies
